language: ruby
before_script:
  - "cp config/travis.database.yml config/database.yml"
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - "bundle exec rake db:nuke"
rvm:
  - 2.2.7
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - yarn --ignore-engines
script:
  - bundle exec rails test