language: ruby
before_script:
  - "cp config/travis.database.yml config/database.yml"
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - "bundle exec rake db:nuke"
rvm:
  - 2.2.7
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - yarn lint
  - yarn test
  - bundle exec rubocop
  - bundle exec rake test