language: ruby
before_script:
  - "cp config/travis.database.yml config/database.yml"
  - "psql -c 'create database myapp_test;' -U postgres"
env: 'POSTGRES_DB_USER=postgres MYSQL_DB_USER=""'
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
