version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 32785 -b '0.0.0.0'
    volumes:
      - .:/CDB3
    ports:
      - "32785:32785"
    depends_on:
      - db
      - packer
  packer:
    build: .
    command: ./bin/webpack-dev-server --progress --inline
    volumes:
      - .:/CDB3
    ports:
      - "3035:3035"